14 preview not available on all tracks
Karlkorv/best-song pull request #28
Opened 2022-05-17 10:36 UTC by gustavakerstrom99

2022-05-17 12:57 UTC, Karlkorv requested changes
Skriv bättre docs + motivering varför koden behövs

2022-05-17 12:57 UTC, Karlkorv commented on src/Data/Spotify.cs
> +    /// Ful kod? Ja
Skriv riktig dokumentation pls

2022-05-17 12:57 UTC, Karlkorv commented on src/Data/Track.cs
> +/// </summary>
Varför har vi denna??

2022-05-17 14:43 UTC, gustavakerstrom commented on src/Data/Track.cs
> +/// </summary>
För att det är fett jobbigt att deserialisa den till ett FullTrack direkt och vi är ändå bara intresserade av preview_url.

2022-05-17 15:00 UTC, merged

2022-05-18 16:48 UTC, Karlkorv reviewed
Bra